export const properties = [
  {
    img: "images1.jpg",
    title: "New / For Sale",
    desc: "modern family home",
    specials: "4 beds | 3 Baths | 2-Car Garage",
    price: "Price on Request",
  },
  {
    img: "images2.jpg",
    title: "New / For rent",
    desc: "loft style apartment",
    specials: "1 bed | 1 Bath | 1- Parking slot",
    price: "75 L",
  },
  {
    img: "images3.jpg",
    title: "renovated / For Sale",
    desc: "three-storey townhouse",
    specials: "5 beds | 3 Baths | 2-Car Garage",
    price: "82.2 L",
  },
  {
    img: "images4.jpg",
    title: "New / sold",
    desc: "modern apartment",
    specials: "2 beds | 2 Baths | 1-Car Garage",
    price: "Price on Request",
  },
  {
    img: "images5.jpg",
    title: "Renovated / sold",
    desc: "victorian family home",
    specials: "5 beds | 4 Baths | 4-Car Garage",
    price: "4.5 Cr.",
  },
  {
    img: "images6.jpg",
    title: "Renovated / sold",
    desc: "Renovated farm house",
    specials: "4 beds | 2 Baths | 2-Car Garage",
    price: "Price on Request",
  },
  {
    img: "images7.jpg",
    title: "Renovated / sold",
    desc: "Renovated farm house",
    specials: "3 beds | 2 Baths | 1-Car Garage",
    price: "2.1 Cr.",
  },
  {
    img: "images9.jpg",
    title: "Renovated / sold",
    desc: "Renovated farm house",
    specials: "4 beds | 1 Baths | 2-Car Garage",
    price: "2 Cr.",
  },
];
